version: "2.2"

services:
  envoy:
    image: envoyproxy/envoy-debug-dev:latest
    ports:
      - "8800:8800"
      - "8081:8081"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  app:
    image: aws_envoy:latest
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: